/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* Mon Mar 18 14:34:14 2024 */

/* parameterized module instance */
uart_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .RCNT( ), .Empty( ), 
    .Full( ), .AlmostEmpty( ), .AlmostFull( ));
